### ISSUE TITLE
Fetching custom schemas

### ISSUE THREAD

**Issue by brycesteinhoff** [iglooanalytics/snowplow-debugger-chrome-extension#1]
It's nice that the browser extension loads schemas and shows whether the data sent validates.

For events/contexts where we use one of our custom schemas, it says "could not fetch schema". Is it possible to configure a public Iglu registry URL so the extension can fetch these schemas too?

**Comment by brycesteinhoff** [comment]
Oh, I just found the option! :)

**Comment by raulgenially** [comment]
Hi @brycesteinhoff did you found the way to work with custom iglus repositories? I have adding my iglu URL, but nothing works
